"""Added flasg in Booking

Revision ID: 2a3cc0f79f03
Revises: 013bec4247ac
Create Date: 2025-04-03 23:04:59.064887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3cc0f79f03'
down_revision = '013bec4247ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###
