"""Edited User Model

Revision ID: c5afdb56b6ff
Revises: 029a1f57d191
Create Date: 2025-03-27 00:37:55.112913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5afdb56b6ff'
down_revision = '029a1f57d191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['admin_user_id'], ['id'])

    # ### end Alembic commands ###
